FROM node:16.15.0 as build

ARG APP_ID={$APP_ID}
ARG APP_SECRET={$APP_SECRET}
ARG ENCODING_AES_KEY={$ENCODING_AES_KEY}
ARG MYSQL_DATABASE_NAME={$MYSQL_DATABASE_NAME}
ARG MYSQL_HOST={$MYSQL_HOST}
ARG MYSQL_PASSWORD={$MYSQL_PASSWORD}
ARG MYSQL_PORT={$MYSQL_PORT}
ARG MYSQL_USERNAME={$MYSQL_USERNAME}
ARG ORIGIN_ID={$ORIGIN_ID}
ARG TOKEN={$TOKEN}

WORKDIR /app

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone

RUN npm i -g pnpm

COPY package.json .
COPY pnpm-lock.yaml .
COPY tsconfig.json .
COPY tsconfig.build.json .
COPY src ./src

RUN export NODE_ENV=prod
RUN export APP_ID=$APP_ID
RUN export APP_SECRET=$APP_SECRET
RUN export ENCODING_AES_KEY=$ENCODING_AES_KEY
RUN export MYSQL_DATABASE_NAME=$MYSQL_DATABASE_NAME
RUN export MYSQL_HOST=$MYSQL_HOST
RUN export MYSQL_PASSWORD=$MYSQL_PASSWORD
RUN export MYSQL_PORT=$MYSQL_PORT
RUN export MYSQL_USERNAME=$MYSQL_USERNAME
RUN export ORIGIN_ID=$ORIGIN_ID
RUN export TOKEN=$TOKEN

RUN echo NODE_ENV

RUN pnpm install
RUN pnpm build

EXPOSE 3000

CMD ["node", "/app/dist/main.js"]

