FROM node:16.15.0 as build

ARG NODE_ENV=prod
ARG APP_ID={$APP_ID}
ARG APP_SECRET={$APP_SECRET}
ARG ENCODING_AES_KEY={$ENCODING_AES_KEY}
ARG MYSQL_DATABASE_NAME={$MYSQL_DATABASE_NAME}
ARG MYSQL_HOST={$MYSQL_HOST}
ARG MYSQL_PASSWORD={$MYSQL_PASSWORD}
ARG MYSQL_PORT={$MYSQL_PORT}
ARG MYSQL_USERNAME={$MYSQL_USERNAME}
ARG ORIGIN_ID={$ORIGIN_ID}
ARG TOKEN={$TOKEN}
ARG REDIS_HOST={$REDIS_HOST}
ARG REDIS_PASSWORD={$REDIS_PASSWORD}
ARG SECRET_ID={$SECRET_ID}
ARG SECRET_KEY={$SECRET_KEY}
ARG BUCKET={$BUCKET}
ARG REGION={$REGION}

WORKDIR /app

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone

RUN npm i -g pnpm

COPY package.json .
COPY nest-cli.json .
COPY pnpm-lock.yaml .
COPY tsconfig.json .
COPY tsconfig.build.json .
COPY entrypoint.sh .
COPY src ./src

ENV NODE_ENV=$NODE_ENV
ENV APP_ID=$APP_ID
ENV APP_SECRET=$APP_SECRET
ENV ENCODING_AES_KEY=$ENCODING_AES_KEY
ENV MYSQL_DATABASE_NAME=$MYSQL_DATABASE_NAME
ENV MYSQL_HOST=$MYSQL_HOST
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_PORT=$MYSQL_PORT
ENV MYSQL_USERNAME=$MYSQL_USERNAME
ENV ORIGIN_ID=$ORIGIN_ID
ENV TOKEN=$TOKEN
ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PASSWORD=$REDIS_PASSWORD
ENV SECRET_ID=$SECRET_ID
ENV SECRET_KEY=$SECRET_KEY
ENV BUCKET=$BUCKET
ENV REGION=$REGION

RUN pnpm install
RUN pnpm build

EXPOSE 3000

RUN chmod -R 777 /app

ENTRYPOINT ["./entrypoint.sh"]

