#!/bin/bash

export NODE_ENV=$NODE_ENV
export APP_ID=$APP_ID
export APP_SECRET=$APP_SECRET
export ENCODING_AES_KEY=$ENCODING_AES_KEY
export MYSQL_DATABASE_NAME=$MYSQL_DATABASE_NAME
export MYSQL_HOST=$MYSQL_HOST
export MYSQL_PASSWORD=$MYSQL_PASSWORD
export MYSQL_PORT=$MYSQL_PORT
export MYSQL_USERNAME=$MYSQL_USERNAME
export ORIGIN_ID=$ORIGIN_ID
export TOKEN=$TOKEN
export SERVER_IP=$SERVER_IP
export REDIS_HOST=$REDIS_HOST
export REDIS_PASSWORD=$REDIS_PASSWORD
export SECRET_ID=$SECRET_ID
export SECRET_KEY=$SECRET_KEY
export BUCKET=$BUCKET
export REGION=$REGION
export PRIVATEKEY=$PRIVATEKEY
export SALT=$SALT
export WEATHER_PRIVATE_KEY=$WEATHER_PRIVATE_KEY
export EXPRESS_CUSTOMER=$EXPRESS_CUSTOMER
export EXPRESS_PRIVATE_KEY=$EXPRESS_PRIVATE_KEY

echo "-------------master server ------------------"
node /app/dist/main.js
