name: Docker Image CI & CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      ENCODING_AES_KEY: ${{ secrets.ENCODING_AES_KEY }}
      MYSQL_DATABASE_NAME: ${{ secrets.MYSQL_DATABASE_NAME }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      ORIGIN_ID: ${{ secrets.ORIGIN_ID }}
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - name: 构建镜像
        run: docker build --build-arg $APP_ID $APP_SECRET $ENCODING_AES_KEY $MYSQL_DATABASE_NAME $MYSQL_HOST $MYSQL_PASSWORD $MYSQL_PORT $MYSQL_USERNAME $ORIGIN_ID $TOKEN --file Dockerfile --tag jpccr.ccs.tencentyun.com/ta_dah/ta_dah .
      - name: 登录 docker hub
        run: echo "${{ secrets.TENCENT_REGISTRY_PASSWORD }}" | docker login jpccr.ccs.tencentyun.com --username=100010215712 --password-stdin
      - name: 镜像推送
        run: docker push jpccr.ccs.tencentyun.com/ta_dah/ta_dah
