name: Docker Image CI & CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: build image
        run: docker build --build-arg "APP_ID=${{ secrets.APP_ID }}" --build-arg "APP_SECRET=${{ secrets.APP_SECRET }}" --build-arg "ENCODING_AES_KEY=${{ secrets.ENCODING_AES_KEY }}" --build-arg "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" --build-arg "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" --build-arg "MYSQL_PORT=${{ secrets.MYSQL_PORT }}" --build-arg "MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}" --build-arg "ORIGIN_ID=${{ secrets.ORIGIN_ID }}" --build-arg "TOKEN=${{ secrets.TOKEN }}" --build-arg "MYSQL_DATABASE_NAME=${{ secrets.MYSQL_DATABASE_NAME }}" --file Dockerfile --tag ccr.ccs.tencentyun.com/cyanthing/ta_dah .
      - name: login tencent image hub
        run: echo "${{ secrets.TENCENT_REGISTRY_PASSWORD }}" | docker login ccr.ccs.tencentyun.com --username=100010215712 --password-stdin
      - name: image push
        run: docker push ccr.ccs.tencentyun.com/cyanthing/ta_dah

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: init ssh and deploy image
        run: |
          eval $(ssh-agent -s)
          echo "${{secrets.SERVER_SSH_PRIV_KEY}}" > deploy.key
          mkdir -p ~/.ssh
          chmod 0600 deploy.key
          ssh-add deploy.key
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          ssh ubuntu@${{secrets.SERVER_IP}} "cd /home/ubuntu && sh deploy.sh"
    needs: build
